[package]
name = "wiki"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bytes = "1.6.1"
clap = "4.5.11"
log = "0.4.22"
phf = "0.11.2"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
refinery = { version = "0.8.14", features = ["tokio-postgres"] }
regex = "1.10.5"
serde_json = "1.0.120"
serde_yaml = "0.9.34"
tokio = { version = "1.39.1", features = ["full"] }
tokio-postgres = "0.7.11"
warp = "0.3.7"

[build-dependencies]
ignore = "0.4.22"
phf_codegen = "0.11.2"
serde_yaml = "0.9.34"

[dev-dependencies]
phf = { version = "0.11.2", features = ["macros"] }
