[package]
name = "wiki"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
phf = "0.11.2"
rand = "0.8.5"
refinery = { version = "0.8.14", features = ["tokio-postgres"] }
regex = "1.10.3"
serde_yaml = "0.9.33"
tokio = { version = "1.36.0", features = ["full"] }
tokio-postgres = "0.7.10"
warp = "0.3.6"

[build-dependencies]
phf_codegen = "0.11.2"
serde_yaml = "0.9.33"

[dev-dependencies]
phf = { version = "0.11.2", features = ["macros"] }
