[package]
name = "wiki"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
clap = "4.5.4"
log = "0.4.21"
phf = "0.11.2"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
refinery = { version = "0.8.14", features = ["tokio-postgres"] }
regex = "1.10.4"
serde_yaml = "0.9.34"
tokio = { version = "1.37.0", features = ["full"] }
tokio-postgres = "0.7.10"
warp = "0.3.7"

[build-dependencies]
phf_codegen = "0.11.2"
serde_yaml = "0.9.34"

[dev-dependencies]
phf = { version = "0.11.2", features = ["macros"] }
