[package]
name = "ci"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.36"
serde_json = "1.0.140"
sha2 = "0.10.8"
