[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
regex = "1.10.6"
reqwest = "0.12.5"
serde_yaml = "0.9.34"
tokio = { version = "1.39.2", features = ["full"] }
