[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
regex = "1.10.3"
reqwest = { version = "0.11.26", features = ["rustls-tls-webpki-roots"] }
serde_yaml = "0.9.33"
tokio = { version = "1.36.0", features = ["full"] }
