name: Node.js Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'

    - name: Install
      run: npm install --omit=dev
      working-directory: ./ui

    - name: Lint
      run: npm run lint
      working-directory: ./ui

    - name: Test
      run: npm run test
      working-directory: ./ui

    - name: Build
      run: npm run build
      working-directory: ./ui
