name: Rust Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Rust version
      run: |
        rustup update 1.77.0        &&\
        rustup default 1.77.0       &&\
        rustup component add clippy

    - name: Lint
      run: cargo clippy --all-targets --all-features

    - name: Test
      run: cargo test
